### ISSUE TITLE
gmt file

### ISSUE THREAD

**Issue by pengyan19** [zqfang/GSEApy#152]
Hello,i met a question as follows:
Traceback (most recent call last):
  File "/public/home/pengyan/anaconda3/envs/gseapy/bin/gseapy", line 10, in <module>
    sys.exit(main())
  File "/public/home/pengyan/anaconda3/envs/gseapy/lib/python3.10/site-packages/gseapy/__main__.py", line 39, in main
    gs.run()
  File "/public/home/pengyan/anaconda3/envs/gseapy/lib/python3.10/site-packages/gseapy/gsea.py", line 417, in run
    gmt = self.load_gmt(gene_list=dat2.index.values, gmt=self.gene_sets)
  File "/public/home/pengyan/anaconda3/envs/gseapy/lib/python3.10/site-packages/gseapy/gsea.py", line 119, in load_gmt
    genesets_dict = self.parse_gmt(gmt)
  File "/public/home/pengyan/anaconda3/envs/gseapy/lib/python3.10/site-packages/gseapy/gsea.py", line 163, in parse_gmt
    raise Exception("No supported gene_sets: %s"%gmt)
Exception: No supported gene_sets: ../gmt.txt

**Comment by zqfang** [comment]
rename your gmt.txt to xxx.gmt
