### ISSUE TITLE
dotplot AttributeError

### ISSUE THREAD

**Issue by ymy948** [zqfang/GSEApy#279]
Python: 3.7.6
GSEApy: 1.1.3

The same issue has been raised before, but it was not resolved.

ax = dotplot(enr.results,
              column="Adjusted P-value",
              x='Gene_set', 
              size=10,
              top_term=5,
              figsize=(3,5),
              title = "KEGG",
              xticklabels_rot=45,
              show_ring=True, 
              marker='o',
             )
Traceback (most recent call last):

  File "<ipython-input-267-c4d5934b20fc>", line 10, in <module>
    marker='o',

  File "D:\anapython\lib\site-packages\gseapy\plot.py", line 1179, in dotplot
    ax = dot.scatter(outer_ring=show_ring)

  File "D:\anapython\lib\site-packages\gseapy\plot.py", line 866, in scatter
    zorder=0,

  File "D:\anapython\lib\site-packages\matplotlib\__init__.py", line 1637, in inner
    return func(*bound.args, **bound.kwargs)

  File "D:\anapython\lib\site-packages\matplotlib\axes\_axes.py", line 4433, in scatter
    self._process_unit_info(xdata=x, ydata=y, kwargs=kwargs)

  File "D:\anapython\lib\site-packages\matplotlib\axes\_base.py", line 2125, in _process_unit_info
    kwargs = _process_single_axis(xdata, self.xaxis, 'xunits', kwargs)

  File "D:\anapython\lib\site-packages\matplotlib\axes\_base.py", line 2118, in _process_single_axis
    axis.set_units(units)

  File "D:\anapython\lib\site-packages\matplotlib\axis.py", line 1573, in set_units
    self._update_axisinfo()

  File "D:\anapython\lib\site-packages\matplotlib\axis.py", line 1510, in _update_axisinfo
    info = self.converter.axisinfo(self.units, self)

  File "D:\anapython\lib\site-packages\matplotlib\category.py", line 93, in axisinfo
    majloc = StrCategoryLocator(unit._mapping)

AttributeError: 'NoneType' object has no attribute '_mapping'

**Comment by zqfang** [comment]
can you show me the matplotlib version ?

**Comment by ymy948** [comment]
> can you show me the matplotlib version ?

Thanks for the reply, my matplotlib version is 3.1.3.

**Comment by zqfang** [comment]
matplotlib 3.1 are quite old (2019). Can you update it with more recent release ?
