### ISSUE TITLE
Problem running with entrez ids

### ISSUE THREAD

**Issue by krassowski** [zqfang/GSEApy#59]
Hi there, many thanks for your great package! I tried to run gsea with entrez ids instead of gene names (using custom gene sets from MSigDB - they offer both symbol-indexed and entrez id indexed signatures sets), however it appears that GSEApy assumes that gene id are always strings. Could you have a look on it?

Here is my traceback:
```python
Traceback (most recent call last):
  File "[...]/bin/gseapy", line 11, in <module>
    sys.exit(main())
  File "[...]/lib/python3.7/site-packages/gseapy/__main__.py", line 41, in main
    gs.run()
  File "[...]/lib/python3.7/site-packages/gseapy/gsea.py", line 420, in run
    gmt=gmt, rank_metric=dat2, permutation_type=self.permutation_type)
  File "[...]/lib/python3.7/site-packages/gseapy/gsea.py", line 270, in _save_results
    rdict['genes'] = ";".join([ g.strip() for g in _genes ])
  File "[...]/lib/python3.7/site-packages/gseapy/gsea.py", line 270, in <listcomp>
    rdict['genes'] = ";".join([ g.strip() for g in _genes ])
AttributeError: 'numpy.int64' object has no attribute 'strip'

```

**Comment by zqfang** [comment]
Sorry, entrez ids input for GSEApy has not been tested before. I made a quick fix, and it should be worked now.

**Comment by krassowski** [comment]
Thank you for your quick replay. I tested it and it works for me now.
