### ISSUE TITLE
replot function bug

### ISSUE THREAD

**Issue by kodayu** [zqfang/GSEApy#74]
Hello, when I use gseapy replot function to replot my GSEA results, it works well on a default geneset, for example, the hallmark, c2,c5 and so on. however, when I use a user-defined gene set, such as enzyme and its substrates. I get an error and I still don't know why?
Traceback (most recent call last):
  File "/home/yukai/bin/gseapy", line 10, in <module>
    sys.exit(main())
  File "/home/yeying/miniconda3/lib/python2.7/site-packages/gseapy/__main__.py", line 30, in main
    rep.run()
  File "/home/yeying/miniconda3/lib/python2.7/site-packages/gseapy/gsea.py", line 761, in run
    rank_metric = self._load_ranking(rank_path)
  File "/home/yeying/miniconda3/lib/python2.7/site-packages/gseapy/gsea.py", line 66, in _load_ranking
    rank_metric.sort_values(by=rank_metric.columns[1], ascending=self.ascending, inplace=True)
  File "/home/yeying/miniconda3/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2084, in __getitem__
    return getitem(key)
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by zqfang** [comment]
So, you rnk file contains '#' as your ids. Pandas just treat the text followed by '#' as comment words.  Your problem have been fixed now, just install the latest PR
