### ISSUE TITLE
Use of gseapy enrichr on local gmt instead of API ?

### ISSUE THREAD

**Issue by agroppi** [zqfang/GSEApy#86]
Hi,
Is it possible to run the following command : 
`Gseapy/bin/gseapy enrichr` on local gmt files (_ie_ not via the API) (I have on my computer a lot of gmt files)
and save all the figures ?
Thanks

**Comment by zqfang** [comment]
Yes, absolutely . see here for examples. 
https://gseapy.readthedocs.io/en/master/gseapy_example.html#2.1.2-Local-mode-of-GO-analysis

This feature is also supported in command line. Just try it.

    gseapy enrichr -g xxx.gmt …….

**Comment by agroppi** [comment]
Thanks but when I try this command : 

```
gseapy enrichr -i /scratch/ag/gene_name_list.txt \
--ds BP2017b \
-g /bank/enrichr/GO_Biological_Process_2017b.gmt \
-v \
-o /scratch/ag//test/Gseapy_analysis
```
I have the error : 

```
Traceback (most recent call last):
  File "/module/apps/gseapy/0.9.13/bin/gseapy", line 10, in <module>
    sys.exit(main())
  File "/module/apps/gseapy/0.9.13/lib/python3.6/site-packages/gseapy/__main__.py", line 69, in main
    enr.run()
  File "/module/apps/gseapy/0.9.13/lib/python3.6/site-packages/gseapy/enrichr.py", line 309, in run
    gss = self.parse_genesets()
  File "/module/apps/gseapy/0.9.13/lib/python3.6/site-packages/gseapy/enrichr.py", line 68, in parse_genesets
    enrichr_library = self.get_libraries()
  File "/module/apps/gseapy/0.9.13/lib/python3.6/site-packages/gseapy/enrichr.py", line 182, in get_libraries
    libs_json = json.loads(requests.get(lib_url).text)
  File "/module/apps/gseapy/0.9.13/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/module/apps/gseapy/0.9.13/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/module/apps/gseapy/0.9.13/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Thanks for your help

**Comment by agroppi** [comment]
A clue : 
By replacing (Enrichr by Enrichr3) in the python script enrichr.py

```
	Line 3: # see: http://amp.pharm.mssm.edu/Enrichr/help#api for API docs
	Line 147:         response = requests.get('http://amp.pharm.mssm.edu/Enrichr/view?userListId=%s' % usr_list_id)
	Line 156:         ADDLIST_URL = 'http://amp.pharm.mssm.edu/%sEnrichr/addList'%self._organism
	Line 160:         RESULTS_URL = 'http://amp.pharm.mssm.edu/%sEnrichr/export'%self._organism
	Line 181:         lib_url='http://amp.pharm.mssm.edu/%sEnrichr/datasetStatistics'%self._organism
	Line 259:         see here: http://amp.pharm.mssm.edu/Enrichr/help#background&q=4
	Line 363:                      see here for details: https://amp.pharm.mssm.edu/modEnrichr
```
by
```
	Line 3: # see: http://amp.pharm.mssm.edu/Enrichr3/help#api for API docs
	Line 147:         response = requests.get('http://amp.pharm.mssm.edu/Enrichr3/view?userListId=%s' % usr_list_id)
	Line 156:         ADDLIST_URL = 'http://amp.pharm.mssm.edu/%sEnrichr3/addList'%self._organism
	Line 160:         RESULTS_URL = 'http://amp.pharm.mssm.edu/%sEnrichr3/export'%self._organism
	Line 181:         lib_url='http://amp.pharm.mssm.edu/%sEnrichr3/datasetStatistics'%self._organism
	Line 259:         see here: http://amp.pharm.mssm.edu/Enrichr3/help#background&q=4
	Line 363:                      see here for details: https://amp.pharm.mssm.edu/modEnrichr
```
It works !

So it seems that despite parameters set to run a local analysis Gseapy enrichr try ton connect to https://amp.pharm.mssm.edu/Enrichr/ and since a fews days this URL is no longer working and replaced by https://amp.pharm.mssm.edu/Enrichr3/

**Comment by zqfang** [comment]
Thanks for letting me know. The Enriochr API have changed without a warning.  I will release a new version very soon. You'er wellcome to make a pull request if you'd like to.

**Comment by agroppi** [comment]
I think that this situation is transitory. They are working on the main server.
But my question was more : is that normal that gseapy enricher tries to connect to https://amp.pharm.mssm.edu/ even for a local analysis ?

**Comment by zqfang** [comment]
For a more flexibale input for `gene_sets` argument, this example could get results much faster than input one  in single run:

```python
    enrichr(... gene_sets=['KEGG_2016','BP2019', 'xxx.gmt1'....], ...)
    # or
    enrichr(... gene_sets="KEGG_2016,BP2019,xxx.gmt,yyy.gmt,....", ....)
```
I could not find another way to do this without connecting to Enrichr server, so far.

**Comment by agroppi** [comment]
OK thanks.
By the way https://amp.pharm.mssm.edu/Enrichr/ is up and running (https://twitter.com/AviMaayan/status/1150908824229990400?s=20)

**Comment by Benfeitas** [comment]
@zqfang I too find that even in local mode it seems `enrichr` is connecting. 

```
enr3 = gp.enrichr(
    gene_list=dlist,
    description='Dn',
    gene_sets=path+'Results/out.gmt',
    background=bkgd,
    verbose=True,
    outdir=path+'Results/gsea/',
    format='png',
    cutoff=0.01
)
#2019-07-30 17:53:41,235 User Defined gene sets is given: /my/path/Results.gmt
#2019-07-30 17:53:41,238 Connecting to Enrichr Server to get latest library names
#2019-07-30 17:53:41,257 Save file of enrichment results: Job Id:5009386664
#2019-07-30 17:53:41,913 Done.
```
