### ISSUE TITLE
Repeat the whole python file the same times as many processes I set

### ISSUE THREAD

**Issue by liugaocn** [zqfang/GSEApy#97]
GSEAPY repeats the whole python file the same times as many processes I set. After repeating the whole python file, it could go to the end. But then I get this "multiprocessing.pool.MaybeEncodingError". 
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Gao/Desktop/GSEA SMARCA4.py", line 52, in <module>
    method='signal_to_noise')
  File "C:\Users\Gao\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gseapy\gsea.py", line 935, in gsea
    gs.run()
  File "C:\Users\Gao\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gseapy\gsea.py", line 421, in run
    processes=self._processes, seed=self.seed)
  File "C:\Users\Gao\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gseapy\algorithm.py", line 375, in gsea_compute_tensor
    gi, cor = temp.get()
  File "C:\Users\Gao\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x0C296850>'. Reason: 'PicklingError("Can't pickle <class 'numpy.core._exceptions.MemoryError'>: attribute lookup MemoryError on numpy.core._exceptions failed")'
```

By the way, even when I set the processes to only 1, it also repeats it, which means it execute the whole program twice. I need some advises. My code is as:
```
print("next move...")
if __name__ == '__main__':
    gene_sets = "KEGG_2019_Human"
    gs_res = gp.gsea(data=df,
                     gene_sets= gene_sets,
                     cls = cls_list,
                     permutation_type='phenotype',
                     permutation_num=1000,
                     outdir= gene_sets + gene_name,
                     no_plot=True,
                     processes=1, seed= 7,
                     method='signal_to_noise')

    print(gs_res.res2d.head())
print("end!")
```
It also get the same Exception mentioned before.

**Comment by zqfang** [comment]
Would you mind tell me which version did you use?

**Comment by liugaocn** [comment]
Thank you. Besides, I noticed that you made a small change to GSEAPLOT. I got "Positive Correlated" texts or something alike before, now I got none, which is definitely a good thing.
